// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wedding.Infrastructure.Context;

namespace Wedding.Infrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20210911104100_FixedGeoDivision")]
    partial class FixedGeoDivision
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "29bd76db-5835-406d-ad1d-7a0901447c18",
                            ConcurrencyStamp = "a0b95bce-5339-4f3d-8fb3-f102166b05a8",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "d7be43da-622c-4cfe-98a9-5a5161120d24",
                            ConcurrencyStamp = "3d1e90ac-eb35-4fd4-b398-4413e18d16b1",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            ConcurrencyStamp = "3e6ce7e9-e045-4b80-b4d8-eddb6b64386a",
                            Name = "Superuser",
                            NormalizedName = "SUPERUSER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "75625814-138e-4831-a1ea-bf58e211adff",
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901447c18"
                        },
                        new
                        {
                            UserId = "75625814-138e-4831-a1ea-bf58e211acmf",
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Wedding.Core.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ArticleCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(600)")
                        .HasMaxLength(600);

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Wedding.Core.Models.ArticleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArticleCategories");
                });

            modelBuilder.Entity("Wedding.Core.Models.ArticleComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShow")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(800)")
                        .HasMaxLength(800);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ParentId");

                    b.ToTable("ArticleComments");
                });

            modelBuilder.Entity("Wedding.Core.Models.ArticleTag", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArticleTags");
                });

            modelBuilder.Entity("Wedding.Core.Models.ContactUsForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactUsForms");
                });

            modelBuilder.Entity("Wedding.Core.Models.GeoDivision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GeoDivisionType")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LatinTitle")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("GeoDivisions");
                });

            modelBuilder.Entity("Wedding.Core.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Wedding.Core.Models.NavigationMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ElementIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentMenuId")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ParentMenuId");

                    b.ToTable("AspNetNavigationMenu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 100,
                            ElementIdentifier = "auth_control",
                            Icon = "Icon",
                            Name = "مجوز دسترسی",
                            Visible = true
                        },
                        new
                        {
                            Id = 2,
                            ActionName = "Index",
                            ControllerName = "Users",
                            ElementIdentifier = "users",
                            Name = "کاربران",
                            ParentMenuId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 3,
                            ActionName = "Create",
                            ControllerName = "Users",
                            ElementIdentifier = "users",
                            Name = "افزودن کابر",
                            ParentMenuId = 2,
                            Visible = false
                        },
                        new
                        {
                            Id = 4,
                            ActionName = "Edit",
                            ControllerName = "Users",
                            ElementIdentifier = "users",
                            Name = "ویرایش کابر",
                            ParentMenuId = 2,
                            Visible = false
                        },
                        new
                        {
                            Id = 5,
                            ActionName = "Delete",
                            ControllerName = "Users",
                            ElementIdentifier = "users",
                            Name = "حذف کابر",
                            ParentMenuId = 2,
                            Visible = false
                        },
                        new
                        {
                            Id = 6,
                            ActionName = "EditRoles",
                            ControllerName = "Users",
                            ElementIdentifier = "users",
                            Name = "ویرایش نقش های کابر",
                            ParentMenuId = 2,
                            Visible = false
                        },
                        new
                        {
                            Id = 7,
                            ActionName = "EditMyProfile",
                            ControllerName = "Users",
                            ElementIdentifier = "users",
                            Name = "ویرایش پروفایل من",
                            ParentMenuId = 2,
                            Visible = false
                        },
                        new
                        {
                            Id = 8,
                            ActionName = "Index",
                            ControllerName = "Roles",
                            ElementIdentifier = "roles",
                            Name = "نقش ها",
                            ParentMenuId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 9,
                            ActionName = "Create",
                            ControllerName = "Roles",
                            ElementIdentifier = "roles",
                            Name = "افزودن نقش",
                            ParentMenuId = 8,
                            Visible = false
                        },
                        new
                        {
                            Id = 10,
                            ActionName = "Edit",
                            ControllerName = "Roles",
                            ElementIdentifier = "roles",
                            Name = "ویرایش نقش",
                            ParentMenuId = 8,
                            Visible = false
                        },
                        new
                        {
                            Id = 11,
                            ActionName = "Delete",
                            ControllerName = "Roles",
                            ElementIdentifier = "roles",
                            Name = "حذف نقش",
                            ParentMenuId = 8,
                            Visible = false
                        },
                        new
                        {
                            Id = 12,
                            ActionName = "EditRolePermission",
                            ControllerName = "Roles",
                            ElementIdentifier = "roles",
                            Name = "ویرایش دسترسی های نقش",
                            ParentMenuId = 8,
                            Visible = false
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 1,
                            ElementIdentifier = "article_control",
                            Icon = "Icon",
                            Name = "مدیریت مطالب",
                            Visible = true
                        },
                        new
                        {
                            Id = 14,
                            ActionName = "Index",
                            ControllerName = "ArticleCategories",
                            ElementIdentifier = "article_categories",
                            Name = "دسته بندی مطالب",
                            ParentMenuId = 13,
                            Visible = true
                        },
                        new
                        {
                            Id = 15,
                            ActionName = "Create",
                            ControllerName = "ArticleCategories",
                            ElementIdentifier = "article_categories",
                            Name = "افزودن دسته بندی",
                            ParentMenuId = 14,
                            Visible = false
                        },
                        new
                        {
                            Id = 16,
                            ActionName = "Edit",
                            ControllerName = "ArticleCategories",
                            ElementIdentifier = "article_categories",
                            Name = "ویرایش دسته بندی",
                            ParentMenuId = 14,
                            Visible = false
                        },
                        new
                        {
                            Id = 17,
                            ActionName = "Delete",
                            ControllerName = "ArticleCategories",
                            ElementIdentifier = "article_categories",
                            Name = "حذف دسته بندی",
                            ParentMenuId = 14,
                            Visible = false
                        },
                        new
                        {
                            Id = 18,
                            ActionName = "Index",
                            ControllerName = "Articles",
                            ElementIdentifier = "articles",
                            Name = "مطالب",
                            ParentMenuId = 13,
                            Visible = true
                        },
                        new
                        {
                            Id = 19,
                            ActionName = "Create",
                            ControllerName = "Articles",
                            ElementIdentifier = "articles",
                            Name = "افزودن مطلب",
                            ParentMenuId = 18,
                            Visible = false
                        },
                        new
                        {
                            Id = 20,
                            ActionName = "Edit",
                            ControllerName = "Articles",
                            ElementIdentifier = "articles",
                            Name = "ویرایش مطلب",
                            ParentMenuId = 18,
                            Visible = false
                        },
                        new
                        {
                            Id = 21,
                            ActionName = "Delete",
                            ControllerName = "Articles",
                            ElementIdentifier = "articles",
                            Name = "حذف مطلب",
                            ParentMenuId = 18,
                            Visible = false
                        },
                        new
                        {
                            Id = 22,
                            ActionName = "Index",
                            ControllerName = "ArticleComments",
                            ElementIdentifier = "articles",
                            Name = "کامنت ها",
                            ParentMenuId = 18,
                            Visible = false
                        },
                        new
                        {
                            Id = 23,
                            ActionName = "Create",
                            ControllerName = "ArticleComments",
                            ElementIdentifier = "articles",
                            Name = "افزودن کامنت",
                            ParentMenuId = 22,
                            Visible = false
                        },
                        new
                        {
                            Id = 24,
                            ActionName = "Edit",
                            ControllerName = "ArticleComments",
                            ElementIdentifier = "articles",
                            Name = "ویرایش کامنت",
                            ParentMenuId = 22,
                            Visible = false
                        },
                        new
                        {
                            Id = 25,
                            ActionName = "Delete",
                            ControllerName = "ArticleComments",
                            ElementIdentifier = "articles",
                            Name = "حذف کامنت",
                            ParentMenuId = 22,
                            Visible = false
                        },
                        new
                        {
                            Id = 26,
                            ActionName = "AnswerComment",
                            ControllerName = "ArticleComments",
                            ElementIdentifier = "articles",
                            Name = "پاسخ دادن به کامنت",
                            ParentMenuId = 22,
                            Visible = false
                        },
                        new
                        {
                            Id = 27,
                            ActionName = "Index",
                            ControllerName = "ContactUsForm",
                            DisplayOrder = 6,
                            ElementIdentifier = "contact_us_form",
                            Name = "فرم تماس با ما",
                            Visible = true
                        },
                        new
                        {
                            Id = 28,
                            ActionName = "Details",
                            ControllerName = "ContactUsForm",
                            ElementIdentifier = "contact_us_form",
                            Name = "مشاهده فرم تماس با ما",
                            Visible = false
                        },
                        new
                        {
                            Id = 29,
                            ActionName = "Index",
                            ControllerName = "StaticContent",
                            DisplayOrder = 99,
                            ElementIdentifier = "static_content",
                            Name = "محتوا ثابت",
                            ParentMenuId = 28,
                            Visible = true
                        });
                });

            modelBuilder.Entity("Wedding.Core.Models.RoleMenuPermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NavigationMenuId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "NavigationMenuId");

                    b.HasIndex("NavigationMenuId");

                    b.ToTable("AspNetRoleMenuPermission");

                    b.HasData(
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 1
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 2
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 3
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 4
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 5
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 6
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 7
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 8
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 9
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 10
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 11
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 12
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 13
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 14
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 15
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 16
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 17
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 18
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 19
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 20
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 21
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 22
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 23
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 24
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 25
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 26
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 27
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 28
                        },
                        new
                        {
                            RoleId = "29bd76db-5835-406d-ad1d-7a0901448abd",
                            NavigationMenuId = 29
                        });
                });

            modelBuilder.Entity("Wedding.Core.Models.SystemParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemParameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2021, 9, 11, 15, 10, 59, 831, DateTimeKind.Local).AddTicks(4764),
                            InsertUser = "SuperUser",
                            IsDeleted = false,
                            Key = "DefaultPassword",
                            Value = "User@123456"
                        });
                });

            modelBuilder.Entity("Wedding.Core.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Wedding.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "75625814-138e-4831-a1ea-bf58e211adff",
                            AccessFailedCount = 0,
                            Avatar = "user-avatar.png",
                            ConcurrencyStamp = "0999369f-cce6-4c74-a264-43963c005e10",
                            Email = "Admin@Admin.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEBnq53N3BOmD07izgQ/5/ZGWu/TPSfaaMJd88cjLMrwaoKybksNIaShS224GYHXqEg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c74f77fa-a597-4aec-8b4c-8ac7975426f5",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = "75625814-138e-4831-a1ea-bf58e211acmf",
                            AccessFailedCount = 0,
                            Avatar = "user-avatar.png",
                            ConcurrencyStamp = "c6acfdf7-6ae9-4693-9153-a42b555d1add",
                            Email = "Superuser@Superuser.com",
                            EmailConfirmed = true,
                            FirstName = "Superuser",
                            LastName = "Superuser",
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERUSER@SUPERUSER.COM",
                            NormalizedUserName = "SUPERUSER",
                            PasswordHash = "AQAAAAEAACcQAAAAEDSMTEMkWycDiwz/B576/cKG6VK9sl0g1tsjBrLKu4PtuRxiRpwvammJyVOxdLH0bg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3ee107bc-3170-4946-bf75-e5e244c36be8",
                            TwoFactorEnabled = false,
                            UserName = "Superuser"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Wedding.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Wedding.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wedding.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Wedding.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wedding.Core.Models.Article", b =>
                {
                    b.HasOne("Wedding.Core.Models.ArticleCategory", "ArticleCategory")
                        .WithMany("Articles")
                        .HasForeignKey("ArticleCategoryId");

                    b.HasOne("Wedding.Core.Models.User", "User")
                        .WithMany("Articles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Wedding.Core.Models.ArticleComment", b =>
                {
                    b.HasOne("Wedding.Core.Models.Article", "Article")
                        .WithMany("ArticleComments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wedding.Core.Models.ArticleComment", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Wedding.Core.Models.ArticleTag", b =>
                {
                    b.HasOne("Wedding.Core.Models.Article", "Article")
                        .WithMany("ArticleTags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wedding.Core.Models.Tag", "Tag")
                        .WithMany("ArticleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wedding.Core.Models.GeoDivision", b =>
                {
                    b.HasOne("Wedding.Core.Models.GeoDivision", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Wedding.Core.Models.NavigationMenu", b =>
                {
                    b.HasOne("Wedding.Core.Models.NavigationMenu", "ParentNavigationMenu")
                        .WithMany()
                        .HasForeignKey("ParentMenuId");
                });

            modelBuilder.Entity("Wedding.Core.Models.RoleMenuPermission", b =>
                {
                    b.HasOne("Wedding.Core.Models.NavigationMenu", "NavigationMenu")
                        .WithMany()
                        .HasForeignKey("NavigationMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
